/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * AchSecCodeEnum to be used.
 */
public enum AchSecCodeEnum {
    CCD,

    PPD,

    TEL,

    WEB,

    POP,

    C21;


    private static TreeMap<String, AchSecCodeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        CCD.value = "CCD";
        PPD.value = "PPD";
        TEL.value = "TEL";
        WEB.value = "WEB";
        POP.value = "POP";
        C21.value = "C21";

        valueMap.put("CCD", CCD);
        valueMap.put("PPD", PPD);
        valueMap.put("TEL", TEL);
        valueMap.put("WEB", WEB);
        valueMap.put("POP", POP);
        valueMap.put("C21", C21);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AchSecCodeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AchSecCodeEnum values to list of string values.
     * @param toConvert The list of AchSecCodeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AchSecCodeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AchSecCodeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 