/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Filter10 type.
 */
public class Filter10 {
    private String accountHolderName;
    private String accountNumber;
    private String accountVaultApiId;
    private String accountvaultC1;
    private String accountvaultC2;
    private String accountvaultC3;
    private String achSecCode;
    private String billingAddress;
    private String billingCity;
    private String billingPhone;
    private String billingState;
    private String billingZip;
    private String contactId;
    private String customerId;
    private String driversLicense;
    private String locationId;
    private String previousAccountVaultApiId;
    private String previousAccountVaultId;
    private String previousTransactionId;
    private String ssn4;
    private String termsAgree;
    private String termsAgreeIp;
    private String title;
    private String accountType;
    private String active;
    private String cauSummaryStatusId;
    private String createdTs;
    private String id;
    private String eSerialNumber;
    private String eTrackData;
    private String eFormat;
    private String eKeyedData;
    private String expiringInMonths;
    private String firstSix;
    private String hasRecurring;
    private String lastFour;
    private String modifiedTs;
    private String paymentMethod;
    private String ticket;
    private String trackData;

    /**
     * Default constructor.
     */
    public Filter10() {
    }

    /**
     * Initialization constructor.
     * @param  accountHolderName  String value for accountHolderName.
     * @param  accountNumber  String value for accountNumber.
     * @param  accountVaultApiId  String value for accountVaultApiId.
     * @param  accountvaultC1  String value for accountvaultC1.
     * @param  accountvaultC2  String value for accountvaultC2.
     * @param  accountvaultC3  String value for accountvaultC3.
     * @param  achSecCode  String value for achSecCode.
     * @param  billingAddress  String value for billingAddress.
     * @param  billingCity  String value for billingCity.
     * @param  billingPhone  String value for billingPhone.
     * @param  billingState  String value for billingState.
     * @param  billingZip  String value for billingZip.
     * @param  contactId  String value for contactId.
     * @param  customerId  String value for customerId.
     * @param  driversLicense  String value for driversLicense.
     * @param  locationId  String value for locationId.
     * @param  previousAccountVaultApiId  String value for previousAccountVaultApiId.
     * @param  previousAccountVaultId  String value for previousAccountVaultId.
     * @param  previousTransactionId  String value for previousTransactionId.
     * @param  ssn4  String value for ssn4.
     * @param  termsAgree  String value for termsAgree.
     * @param  termsAgreeIp  String value for termsAgreeIp.
     * @param  title  String value for title.
     * @param  accountType  String value for accountType.
     * @param  active  String value for active.
     * @param  cauSummaryStatusId  String value for cauSummaryStatusId.
     * @param  createdTs  String value for createdTs.
     * @param  id  String value for id.
     * @param  eSerialNumber  String value for eSerialNumber.
     * @param  eTrackData  String value for eTrackData.
     * @param  eFormat  String value for eFormat.
     * @param  eKeyedData  String value for eKeyedData.
     * @param  expiringInMonths  String value for expiringInMonths.
     * @param  firstSix  String value for firstSix.
     * @param  hasRecurring  String value for hasRecurring.
     * @param  lastFour  String value for lastFour.
     * @param  modifiedTs  String value for modifiedTs.
     * @param  paymentMethod  String value for paymentMethod.
     * @param  ticket  String value for ticket.
     * @param  trackData  String value for trackData.
     */
    public Filter10(
            String accountHolderName,
            String accountNumber,
            String accountVaultApiId,
            String accountvaultC1,
            String accountvaultC2,
            String accountvaultC3,
            String achSecCode,
            String billingAddress,
            String billingCity,
            String billingPhone,
            String billingState,
            String billingZip,
            String contactId,
            String customerId,
            String driversLicense,
            String locationId,
            String previousAccountVaultApiId,
            String previousAccountVaultId,
            String previousTransactionId,
            String ssn4,
            String termsAgree,
            String termsAgreeIp,
            String title,
            String accountType,
            String active,
            String cauSummaryStatusId,
            String createdTs,
            String id,
            String eSerialNumber,
            String eTrackData,
            String eFormat,
            String eKeyedData,
            String expiringInMonths,
            String firstSix,
            String hasRecurring,
            String lastFour,
            String modifiedTs,
            String paymentMethod,
            String ticket,
            String trackData) {
        this.accountHolderName = accountHolderName;
        this.accountNumber = accountNumber;
        this.accountVaultApiId = accountVaultApiId;
        this.accountvaultC1 = accountvaultC1;
        this.accountvaultC2 = accountvaultC2;
        this.accountvaultC3 = accountvaultC3;
        this.achSecCode = achSecCode;
        this.billingAddress = billingAddress;
        this.billingCity = billingCity;
        this.billingPhone = billingPhone;
        this.billingState = billingState;
        this.billingZip = billingZip;
        this.contactId = contactId;
        this.customerId = customerId;
        this.driversLicense = driversLicense;
        this.locationId = locationId;
        this.previousAccountVaultApiId = previousAccountVaultApiId;
        this.previousAccountVaultId = previousAccountVaultId;
        this.previousTransactionId = previousTransactionId;
        this.ssn4 = ssn4;
        this.termsAgree = termsAgree;
        this.termsAgreeIp = termsAgreeIp;
        this.title = title;
        this.accountType = accountType;
        this.active = active;
        this.cauSummaryStatusId = cauSummaryStatusId;
        this.createdTs = createdTs;
        this.id = id;
        this.eSerialNumber = eSerialNumber;
        this.eTrackData = eTrackData;
        this.eFormat = eFormat;
        this.eKeyedData = eKeyedData;
        this.expiringInMonths = expiringInMonths;
        this.firstSix = firstSix;
        this.hasRecurring = hasRecurring;
        this.lastFour = lastFour;
        this.modifiedTs = modifiedTs;
        this.paymentMethod = paymentMethod;
        this.ticket = ticket;
        this.trackData = trackData;
    }

    /**
     * Getter for AccountHolderName.
     * @return Returns the String
     */
    @JsonGetter("account_holder_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountHolderName() {
        return accountHolderName;
    }

    /**
     * Setter for AccountHolderName.
     * @param accountHolderName Value for String
     */
    @JsonSetter("account_holder_name")
    public void setAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }

    /**
     * Getter for AccountNumber.
     * @return Returns the String
     */
    @JsonGetter("account_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * @param accountNumber Value for String
     */
    @JsonSetter("account_number")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for AccountVaultApiId.
     * @return Returns the String
     */
    @JsonGetter("account_vault_api_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountVaultApiId() {
        return accountVaultApiId;
    }

    /**
     * Setter for AccountVaultApiId.
     * @param accountVaultApiId Value for String
     */
    @JsonSetter("account_vault_api_id")
    public void setAccountVaultApiId(String accountVaultApiId) {
        this.accountVaultApiId = accountVaultApiId;
    }

    /**
     * Getter for AccountvaultC1.
     * @return Returns the String
     */
    @JsonGetter("accountvault_c1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountvaultC1() {
        return accountvaultC1;
    }

    /**
     * Setter for AccountvaultC1.
     * @param accountvaultC1 Value for String
     */
    @JsonSetter("accountvault_c1")
    public void setAccountvaultC1(String accountvaultC1) {
        this.accountvaultC1 = accountvaultC1;
    }

    /**
     * Getter for AccountvaultC2.
     * @return Returns the String
     */
    @JsonGetter("accountvault_c2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountvaultC2() {
        return accountvaultC2;
    }

    /**
     * Setter for AccountvaultC2.
     * @param accountvaultC2 Value for String
     */
    @JsonSetter("accountvault_c2")
    public void setAccountvaultC2(String accountvaultC2) {
        this.accountvaultC2 = accountvaultC2;
    }

    /**
     * Getter for AccountvaultC3.
     * @return Returns the String
     */
    @JsonGetter("accountvault_c3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountvaultC3() {
        return accountvaultC3;
    }

    /**
     * Setter for AccountvaultC3.
     * @param accountvaultC3 Value for String
     */
    @JsonSetter("accountvault_c3")
    public void setAccountvaultC3(String accountvaultC3) {
        this.accountvaultC3 = accountvaultC3;
    }

    /**
     * Getter for AchSecCode.
     * @return Returns the String
     */
    @JsonGetter("ach_sec_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAchSecCode() {
        return achSecCode;
    }

    /**
     * Setter for AchSecCode.
     * @param achSecCode Value for String
     */
    @JsonSetter("ach_sec_code")
    public void setAchSecCode(String achSecCode) {
        this.achSecCode = achSecCode;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the String
     */
    @JsonGetter("billing_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for String
     */
    @JsonSetter("billing_address")
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for BillingCity.
     * @return Returns the String
     */
    @JsonGetter("billing_city")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingCity() {
        return billingCity;
    }

    /**
     * Setter for BillingCity.
     * @param billingCity Value for String
     */
    @JsonSetter("billing_city")
    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity;
    }

    /**
     * Getter for BillingPhone.
     * @return Returns the String
     */
    @JsonGetter("billing_phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingPhone() {
        return billingPhone;
    }

    /**
     * Setter for BillingPhone.
     * @param billingPhone Value for String
     */
    @JsonSetter("billing_phone")
    public void setBillingPhone(String billingPhone) {
        this.billingPhone = billingPhone;
    }

    /**
     * Getter for BillingState.
     * @return Returns the String
     */
    @JsonGetter("billing_state")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingState() {
        return billingState;
    }

    /**
     * Setter for BillingState.
     * @param billingState Value for String
     */
    @JsonSetter("billing_state")
    public void setBillingState(String billingState) {
        this.billingState = billingState;
    }

    /**
     * Getter for BillingZip.
     * @return Returns the String
     */
    @JsonGetter("billing_zip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingZip() {
        return billingZip;
    }

    /**
     * Setter for BillingZip.
     * @param billingZip Value for String
     */
    @JsonSetter("billing_zip")
    public void setBillingZip(String billingZip) {
        this.billingZip = billingZip;
    }

    /**
     * Getter for ContactId.
     * @return Returns the String
     */
    @JsonGetter("contact_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getContactId() {
        return contactId;
    }

    /**
     * Setter for ContactId.
     * @param contactId Value for String
     */
    @JsonSetter("contact_id")
    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    /**
     * Getter for CustomerId.
     * @return Returns the String
     */
    @JsonGetter("customer_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Setter for CustomerId.
     * @param customerId Value for String
     */
    @JsonSetter("customer_id")
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for DriversLicense.
     * @return Returns the String
     */
    @JsonGetter("drivers_license")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDriversLicense() {
        return driversLicense;
    }

    /**
     * Setter for DriversLicense.
     * @param driversLicense Value for String
     */
    @JsonSetter("drivers_license")
    public void setDriversLicense(String driversLicense) {
        this.driversLicense = driversLicense;
    }

    /**
     * Getter for LocationId.
     * @return Returns the String
     */
    @JsonGetter("location_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLocationId() {
        return locationId;
    }

    /**
     * Setter for LocationId.
     * @param locationId Value for String
     */
    @JsonSetter("location_id")
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for PreviousAccountVaultApiId.
     * @return Returns the String
     */
    @JsonGetter("previous_account_vault_api_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPreviousAccountVaultApiId() {
        return previousAccountVaultApiId;
    }

    /**
     * Setter for PreviousAccountVaultApiId.
     * @param previousAccountVaultApiId Value for String
     */
    @JsonSetter("previous_account_vault_api_id")
    public void setPreviousAccountVaultApiId(String previousAccountVaultApiId) {
        this.previousAccountVaultApiId = previousAccountVaultApiId;
    }

    /**
     * Getter for PreviousAccountVaultId.
     * @return Returns the String
     */
    @JsonGetter("previous_account_vault_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPreviousAccountVaultId() {
        return previousAccountVaultId;
    }

    /**
     * Setter for PreviousAccountVaultId.
     * @param previousAccountVaultId Value for String
     */
    @JsonSetter("previous_account_vault_id")
    public void setPreviousAccountVaultId(String previousAccountVaultId) {
        this.previousAccountVaultId = previousAccountVaultId;
    }

    /**
     * Getter for PreviousTransactionId.
     * @return Returns the String
     */
    @JsonGetter("previous_transaction_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPreviousTransactionId() {
        return previousTransactionId;
    }

    /**
     * Setter for PreviousTransactionId.
     * @param previousTransactionId Value for String
     */
    @JsonSetter("previous_transaction_id")
    public void setPreviousTransactionId(String previousTransactionId) {
        this.previousTransactionId = previousTransactionId;
    }

    /**
     * Getter for Ssn4.
     * @return Returns the String
     */
    @JsonGetter("ssn4")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSsn4() {
        return ssn4;
    }

    /**
     * Setter for Ssn4.
     * @param ssn4 Value for String
     */
    @JsonSetter("ssn4")
    public void setSsn4(String ssn4) {
        this.ssn4 = ssn4;
    }

    /**
     * Getter for TermsAgree.
     * @return Returns the String
     */
    @JsonGetter("terms_agree")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsAgree() {
        return termsAgree;
    }

    /**
     * Setter for TermsAgree.
     * @param termsAgree Value for String
     */
    @JsonSetter("terms_agree")
    public void setTermsAgree(String termsAgree) {
        this.termsAgree = termsAgree;
    }

    /**
     * Getter for TermsAgreeIp.
     * @return Returns the String
     */
    @JsonGetter("terms_agree_ip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsAgreeIp() {
        return termsAgreeIp;
    }

    /**
     * Setter for TermsAgreeIp.
     * @param termsAgreeIp Value for String
     */
    @JsonSetter("terms_agree_ip")
    public void setTermsAgreeIp(String termsAgreeIp) {
        this.termsAgreeIp = termsAgreeIp;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for AccountType.
     * @return Returns the String
     */
    @JsonGetter("account_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountType() {
        return accountType;
    }

    /**
     * Setter for AccountType.
     * @param accountType Value for String
     */
    @JsonSetter("account_type")
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Getter for Active.
     * @return Returns the String
     */
    @JsonGetter("active")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getActive() {
        return active;
    }

    /**
     * Setter for Active.
     * @param active Value for String
     */
    @JsonSetter("active")
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * Getter for CauSummaryStatusId.
     * @return Returns the String
     */
    @JsonGetter("cau_summary_status_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCauSummaryStatusId() {
        return cauSummaryStatusId;
    }

    /**
     * Setter for CauSummaryStatusId.
     * @param cauSummaryStatusId Value for String
     */
    @JsonSetter("cau_summary_status_id")
    public void setCauSummaryStatusId(String cauSummaryStatusId) {
        this.cauSummaryStatusId = cauSummaryStatusId;
    }

    /**
     * Getter for CreatedTs.
     * @return Returns the String
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedTs() {
        return createdTs;
    }

    /**
     * Setter for CreatedTs.
     * @param createdTs Value for String
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(String createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ESerialNumber.
     * @return Returns the String
     */
    @JsonGetter("e_serial_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getESerialNumber() {
        return eSerialNumber;
    }

    /**
     * Setter for ESerialNumber.
     * @param eSerialNumber Value for String
     */
    @JsonSetter("e_serial_number")
    public void setESerialNumber(String eSerialNumber) {
        this.eSerialNumber = eSerialNumber;
    }

    /**
     * Getter for ETrackData.
     * @return Returns the String
     */
    @JsonGetter("e_track_data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getETrackData() {
        return eTrackData;
    }

    /**
     * Setter for ETrackData.
     * @param eTrackData Value for String
     */
    @JsonSetter("e_track_data")
    public void setETrackData(String eTrackData) {
        this.eTrackData = eTrackData;
    }

    /**
     * Getter for EFormat.
     * @return Returns the String
     */
    @JsonGetter("e_format")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEFormat() {
        return eFormat;
    }

    /**
     * Setter for EFormat.
     * @param eFormat Value for String
     */
    @JsonSetter("e_format")
    public void setEFormat(String eFormat) {
        this.eFormat = eFormat;
    }

    /**
     * Getter for EKeyedData.
     * @return Returns the String
     */
    @JsonGetter("e_keyed_data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEKeyedData() {
        return eKeyedData;
    }

    /**
     * Setter for EKeyedData.
     * @param eKeyedData Value for String
     */
    @JsonSetter("e_keyed_data")
    public void setEKeyedData(String eKeyedData) {
        this.eKeyedData = eKeyedData;
    }

    /**
     * Getter for ExpiringInMonths.
     * @return Returns the String
     */
    @JsonGetter("expiring_in_months")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExpiringInMonths() {
        return expiringInMonths;
    }

    /**
     * Setter for ExpiringInMonths.
     * @param expiringInMonths Value for String
     */
    @JsonSetter("expiring_in_months")
    public void setExpiringInMonths(String expiringInMonths) {
        this.expiringInMonths = expiringInMonths;
    }

    /**
     * Getter for FirstSix.
     * @return Returns the String
     */
    @JsonGetter("first_six")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirstSix() {
        return firstSix;
    }

    /**
     * Setter for FirstSix.
     * @param firstSix Value for String
     */
    @JsonSetter("first_six")
    public void setFirstSix(String firstSix) {
        this.firstSix = firstSix;
    }

    /**
     * Getter for HasRecurring.
     * @return Returns the String
     */
    @JsonGetter("has_recurring")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHasRecurring() {
        return hasRecurring;
    }

    /**
     * Setter for HasRecurring.
     * @param hasRecurring Value for String
     */
    @JsonSetter("has_recurring")
    public void setHasRecurring(String hasRecurring) {
        this.hasRecurring = hasRecurring;
    }

    /**
     * Getter for LastFour.
     * @return Returns the String
     */
    @JsonGetter("last_four")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastFour() {
        return lastFour;
    }

    /**
     * Setter for LastFour.
     * @param lastFour Value for String
     */
    @JsonSetter("last_four")
    public void setLastFour(String lastFour) {
        this.lastFour = lastFour;
    }

    /**
     * Getter for ModifiedTs.
     * @return Returns the String
     */
    @JsonGetter("modified_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getModifiedTs() {
        return modifiedTs;
    }

    /**
     * Setter for ModifiedTs.
     * @param modifiedTs Value for String
     */
    @JsonSetter("modified_ts")
    public void setModifiedTs(String modifiedTs) {
        this.modifiedTs = modifiedTs;
    }

    /**
     * Getter for PaymentMethod.
     * @return Returns the String
     */
    @JsonGetter("payment_method")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Setter for PaymentMethod.
     * @param paymentMethod Value for String
     */
    @JsonSetter("payment_method")
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * Getter for Ticket.
     * @return Returns the String
     */
    @JsonGetter("ticket")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTicket() {
        return ticket;
    }

    /**
     * Setter for Ticket.
     * @param ticket Value for String
     */
    @JsonSetter("ticket")
    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    /**
     * Getter for TrackData.
     * @return Returns the String
     */
    @JsonGetter("track_data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTrackData() {
        return trackData;
    }

    /**
     * Setter for TrackData.
     * @param trackData Value for String
     */
    @JsonSetter("track_data")
    public void setTrackData(String trackData) {
        this.trackData = trackData;
    }

    /**
     * Converts this Filter10 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Filter10 [" + "accountHolderName=" + accountHolderName + ", accountNumber="
                + accountNumber + ", accountVaultApiId=" + accountVaultApiId + ", accountvaultC1="
                + accountvaultC1 + ", accountvaultC2=" + accountvaultC2 + ", accountvaultC3="
                + accountvaultC3 + ", achSecCode=" + achSecCode + ", billingAddress="
                + billingAddress + ", billingCity=" + billingCity + ", billingPhone=" + billingPhone
                + ", billingState=" + billingState + ", billingZip=" + billingZip + ", contactId="
                + contactId + ", customerId=" + customerId + ", driversLicense=" + driversLicense
                + ", locationId=" + locationId + ", previousAccountVaultApiId="
                + previousAccountVaultApiId + ", previousAccountVaultId=" + previousAccountVaultId
                + ", previousTransactionId=" + previousTransactionId + ", ssn4=" + ssn4
                + ", termsAgree=" + termsAgree + ", termsAgreeIp=" + termsAgreeIp + ", title="
                + title + ", accountType=" + accountType + ", active=" + active
                + ", cauSummaryStatusId=" + cauSummaryStatusId + ", createdTs=" + createdTs
                + ", id=" + id + ", eSerialNumber=" + eSerialNumber + ", eTrackData=" + eTrackData
                + ", eFormat=" + eFormat + ", eKeyedData=" + eKeyedData + ", expiringInMonths="
                + expiringInMonths + ", firstSix=" + firstSix + ", hasRecurring=" + hasRecurring
                + ", lastFour=" + lastFour + ", modifiedTs=" + modifiedTs + ", paymentMethod="
                + paymentMethod + ", ticket=" + ticket + ", trackData=" + trackData + "]";
    }

    /**
     * Builds a new {@link Filter10.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Filter10.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountHolderName(getAccountHolderName())
                .accountNumber(getAccountNumber())
                .accountVaultApiId(getAccountVaultApiId())
                .accountvaultC1(getAccountvaultC1())
                .accountvaultC2(getAccountvaultC2())
                .accountvaultC3(getAccountvaultC3())
                .achSecCode(getAchSecCode())
                .billingAddress(getBillingAddress())
                .billingCity(getBillingCity())
                .billingPhone(getBillingPhone())
                .billingState(getBillingState())
                .billingZip(getBillingZip())
                .contactId(getContactId())
                .customerId(getCustomerId())
                .driversLicense(getDriversLicense())
                .locationId(getLocationId())
                .previousAccountVaultApiId(getPreviousAccountVaultApiId())
                .previousAccountVaultId(getPreviousAccountVaultId())
                .previousTransactionId(getPreviousTransactionId())
                .ssn4(getSsn4())
                .termsAgree(getTermsAgree())
                .termsAgreeIp(getTermsAgreeIp())
                .title(getTitle())
                .accountType(getAccountType())
                .active(getActive())
                .cauSummaryStatusId(getCauSummaryStatusId())
                .createdTs(getCreatedTs())
                .id(getId())
                .eSerialNumber(getESerialNumber())
                .eTrackData(getETrackData())
                .eFormat(getEFormat())
                .eKeyedData(getEKeyedData())
                .expiringInMonths(getExpiringInMonths())
                .firstSix(getFirstSix())
                .hasRecurring(getHasRecurring())
                .lastFour(getLastFour())
                .modifiedTs(getModifiedTs())
                .paymentMethod(getPaymentMethod())
                .ticket(getTicket())
                .trackData(getTrackData());
        return builder;
    }

    /**
     * Class to build instances of {@link Filter10}.
     */
    public static class Builder {
        private String accountHolderName;
        private String accountNumber;
        private String accountVaultApiId;
        private String accountvaultC1;
        private String accountvaultC2;
        private String accountvaultC3;
        private String achSecCode;
        private String billingAddress;
        private String billingCity;
        private String billingPhone;
        private String billingState;
        private String billingZip;
        private String contactId;
        private String customerId;
        private String driversLicense;
        private String locationId;
        private String previousAccountVaultApiId;
        private String previousAccountVaultId;
        private String previousTransactionId;
        private String ssn4;
        private String termsAgree;
        private String termsAgreeIp;
        private String title;
        private String accountType;
        private String active;
        private String cauSummaryStatusId;
        private String createdTs;
        private String id;
        private String eSerialNumber;
        private String eTrackData;
        private String eFormat;
        private String eKeyedData;
        private String expiringInMonths;
        private String firstSix;
        private String hasRecurring;
        private String lastFour;
        private String modifiedTs;
        private String paymentMethod;
        private String ticket;
        private String trackData;



        /**
         * Setter for accountHolderName.
         * @param  accountHolderName  String value for accountHolderName.
         * @return Builder
         */
        public Builder accountHolderName(String accountHolderName) {
            this.accountHolderName = accountHolderName;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for accountVaultApiId.
         * @param  accountVaultApiId  String value for accountVaultApiId.
         * @return Builder
         */
        public Builder accountVaultApiId(String accountVaultApiId) {
            this.accountVaultApiId = accountVaultApiId;
            return this;
        }

        /**
         * Setter for accountvaultC1.
         * @param  accountvaultC1  String value for accountvaultC1.
         * @return Builder
         */
        public Builder accountvaultC1(String accountvaultC1) {
            this.accountvaultC1 = accountvaultC1;
            return this;
        }

        /**
         * Setter for accountvaultC2.
         * @param  accountvaultC2  String value for accountvaultC2.
         * @return Builder
         */
        public Builder accountvaultC2(String accountvaultC2) {
            this.accountvaultC2 = accountvaultC2;
            return this;
        }

        /**
         * Setter for accountvaultC3.
         * @param  accountvaultC3  String value for accountvaultC3.
         * @return Builder
         */
        public Builder accountvaultC3(String accountvaultC3) {
            this.accountvaultC3 = accountvaultC3;
            return this;
        }

        /**
         * Setter for achSecCode.
         * @param  achSecCode  String value for achSecCode.
         * @return Builder
         */
        public Builder achSecCode(String achSecCode) {
            this.achSecCode = achSecCode;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  String value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(String billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for billingCity.
         * @param  billingCity  String value for billingCity.
         * @return Builder
         */
        public Builder billingCity(String billingCity) {
            this.billingCity = billingCity;
            return this;
        }

        /**
         * Setter for billingPhone.
         * @param  billingPhone  String value for billingPhone.
         * @return Builder
         */
        public Builder billingPhone(String billingPhone) {
            this.billingPhone = billingPhone;
            return this;
        }

        /**
         * Setter for billingState.
         * @param  billingState  String value for billingState.
         * @return Builder
         */
        public Builder billingState(String billingState) {
            this.billingState = billingState;
            return this;
        }

        /**
         * Setter for billingZip.
         * @param  billingZip  String value for billingZip.
         * @return Builder
         */
        public Builder billingZip(String billingZip) {
            this.billingZip = billingZip;
            return this;
        }

        /**
         * Setter for contactId.
         * @param  contactId  String value for contactId.
         * @return Builder
         */
        public Builder contactId(String contactId) {
            this.contactId = contactId;
            return this;
        }

        /**
         * Setter for customerId.
         * @param  customerId  String value for customerId.
         * @return Builder
         */
        public Builder customerId(String customerId) {
            this.customerId = customerId;
            return this;
        }

        /**
         * Setter for driversLicense.
         * @param  driversLicense  String value for driversLicense.
         * @return Builder
         */
        public Builder driversLicense(String driversLicense) {
            this.driversLicense = driversLicense;
            return this;
        }

        /**
         * Setter for locationId.
         * @param  locationId  String value for locationId.
         * @return Builder
         */
        public Builder locationId(String locationId) {
            this.locationId = locationId;
            return this;
        }

        /**
         * Setter for previousAccountVaultApiId.
         * @param  previousAccountVaultApiId  String value for previousAccountVaultApiId.
         * @return Builder
         */
        public Builder previousAccountVaultApiId(String previousAccountVaultApiId) {
            this.previousAccountVaultApiId = previousAccountVaultApiId;
            return this;
        }

        /**
         * Setter for previousAccountVaultId.
         * @param  previousAccountVaultId  String value for previousAccountVaultId.
         * @return Builder
         */
        public Builder previousAccountVaultId(String previousAccountVaultId) {
            this.previousAccountVaultId = previousAccountVaultId;
            return this;
        }

        /**
         * Setter for previousTransactionId.
         * @param  previousTransactionId  String value for previousTransactionId.
         * @return Builder
         */
        public Builder previousTransactionId(String previousTransactionId) {
            this.previousTransactionId = previousTransactionId;
            return this;
        }

        /**
         * Setter for ssn4.
         * @param  ssn4  String value for ssn4.
         * @return Builder
         */
        public Builder ssn4(String ssn4) {
            this.ssn4 = ssn4;
            return this;
        }

        /**
         * Setter for termsAgree.
         * @param  termsAgree  String value for termsAgree.
         * @return Builder
         */
        public Builder termsAgree(String termsAgree) {
            this.termsAgree = termsAgree;
            return this;
        }

        /**
         * Setter for termsAgreeIp.
         * @param  termsAgreeIp  String value for termsAgreeIp.
         * @return Builder
         */
        public Builder termsAgreeIp(String termsAgreeIp) {
            this.termsAgreeIp = termsAgreeIp;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for accountType.
         * @param  accountType  String value for accountType.
         * @return Builder
         */
        public Builder accountType(String accountType) {
            this.accountType = accountType;
            return this;
        }

        /**
         * Setter for active.
         * @param  active  String value for active.
         * @return Builder
         */
        public Builder active(String active) {
            this.active = active;
            return this;
        }

        /**
         * Setter for cauSummaryStatusId.
         * @param  cauSummaryStatusId  String value for cauSummaryStatusId.
         * @return Builder
         */
        public Builder cauSummaryStatusId(String cauSummaryStatusId) {
            this.cauSummaryStatusId = cauSummaryStatusId;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  String value for createdTs.
         * @return Builder
         */
        public Builder createdTs(String createdTs) {
            this.createdTs = createdTs;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for eSerialNumber.
         * @param  eSerialNumber  String value for eSerialNumber.
         * @return Builder
         */
        public Builder eSerialNumber(String eSerialNumber) {
            this.eSerialNumber = eSerialNumber;
            return this;
        }

        /**
         * Setter for eTrackData.
         * @param  eTrackData  String value for eTrackData.
         * @return Builder
         */
        public Builder eTrackData(String eTrackData) {
            this.eTrackData = eTrackData;
            return this;
        }

        /**
         * Setter for eFormat.
         * @param  eFormat  String value for eFormat.
         * @return Builder
         */
        public Builder eFormat(String eFormat) {
            this.eFormat = eFormat;
            return this;
        }

        /**
         * Setter for eKeyedData.
         * @param  eKeyedData  String value for eKeyedData.
         * @return Builder
         */
        public Builder eKeyedData(String eKeyedData) {
            this.eKeyedData = eKeyedData;
            return this;
        }

        /**
         * Setter for expiringInMonths.
         * @param  expiringInMonths  String value for expiringInMonths.
         * @return Builder
         */
        public Builder expiringInMonths(String expiringInMonths) {
            this.expiringInMonths = expiringInMonths;
            return this;
        }

        /**
         * Setter for firstSix.
         * @param  firstSix  String value for firstSix.
         * @return Builder
         */
        public Builder firstSix(String firstSix) {
            this.firstSix = firstSix;
            return this;
        }

        /**
         * Setter for hasRecurring.
         * @param  hasRecurring  String value for hasRecurring.
         * @return Builder
         */
        public Builder hasRecurring(String hasRecurring) {
            this.hasRecurring = hasRecurring;
            return this;
        }

        /**
         * Setter for lastFour.
         * @param  lastFour  String value for lastFour.
         * @return Builder
         */
        public Builder lastFour(String lastFour) {
            this.lastFour = lastFour;
            return this;
        }

        /**
         * Setter for modifiedTs.
         * @param  modifiedTs  String value for modifiedTs.
         * @return Builder
         */
        public Builder modifiedTs(String modifiedTs) {
            this.modifiedTs = modifiedTs;
            return this;
        }

        /**
         * Setter for paymentMethod.
         * @param  paymentMethod  String value for paymentMethod.
         * @return Builder
         */
        public Builder paymentMethod(String paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * Setter for ticket.
         * @param  ticket  String value for ticket.
         * @return Builder
         */
        public Builder ticket(String ticket) {
            this.ticket = ticket;
            return this;
        }

        /**
         * Setter for trackData.
         * @param  trackData  String value for trackData.
         * @return Builder
         */
        public Builder trackData(String trackData) {
            this.trackData = trackData;
            return this;
        }

        /**
         * Builds a new {@link Filter10} object using the set fields.
         * @return {@link Filter10}
         */
        public Filter10 build() {
            return new Filter10(accountHolderName, accountNumber, accountVaultApiId, accountvaultC1,
                    accountvaultC2, accountvaultC3, achSecCode, billingAddress, billingCity,
                    billingPhone, billingState, billingZip, contactId, customerId, driversLicense,
                    locationId, previousAccountVaultApiId, previousAccountVaultId,
                    previousTransactionId, ssn4, termsAgree, termsAgreeIp, title, accountType,
                    active, cauSummaryStatusId, createdTs, id, eSerialNumber, eTrackData, eFormat,
                    eKeyedData, expiringInMonths, firstSix, hasRecurring, lastFour, modifiedTs,
                    paymentMethod, ticket, trackData);
        }
    }
}
