/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PaymentMethod2Enum to be used.
 */
public enum PaymentMethod2Enum {
    CC,

    ACH;


    private static TreeMap<String, PaymentMethod2Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        CC.value = "cc";
        ACH.value = "ach";

        valueMap.put("cc", CC);
        valueMap.put("ach", ACH);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static PaymentMethod2Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PaymentMethod2Enum values to list of string values.
     * @param toConvert The list of PaymentMethod2Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PaymentMethod2Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PaymentMethod2Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 