/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResponseQuickInvoice type.
 */
public class ResponseQuickInvoice {
    private String type;
    private Data7 data;

    /**
     * Default constructor.
     */
    public ResponseQuickInvoice() {
        type = "QuickInvoice";
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  data  Data7 value for data.
     */
    public ResponseQuickInvoice(
            String type,
            Data7 data) {
        this.type = type;
        this.data = data;
    }

    /**
     * Getter for Type.
     * Resource Type
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Resource Type
     * @param type Value for String
     */
    @JsonSetter("type")
    private void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Data.
     * @return Returns the Data7
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data7 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data7
     */
    @JsonSetter("data")
    public void setData(Data7 data) {
        this.data = data;
    }

    /**
     * Converts this ResponseQuickInvoice into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseQuickInvoice [" + "type=" + type + ", data=" + data + "]";
    }

    /**
     * Builds a new {@link ResponseQuickInvoice.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseQuickInvoice.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type)
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseQuickInvoice}.
     */
    public static class Builder {
        private String type = "QuickInvoice";
        private Data7 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         */
        public Builder(String type) {
            this.type = type;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Data7 value for data.
         * @return Builder
         */
        public Builder data(Data7 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link ResponseQuickInvoice} object using the set fields.
         * @return {@link ResponseQuickInvoice}
         */
        public ResponseQuickInvoice build() {
            return new ResponseQuickInvoice(type, data);
        }
    }
}
