/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Sort8 type.
 */
public class Sort8 {
    private LocationIdEnum locationId;
    private TitleEnum title;
    private IdEnum id;
    private CreatedTsEnum createdTs;
    private ModifiedTsEnum modifiedTs;

    /**
     * Default constructor.
     */
    public Sort8() {
    }

    /**
     * Initialization constructor.
     * @param  locationId  LocationIdEnum value for locationId.
     * @param  title  TitleEnum value for title.
     * @param  id  IdEnum value for id.
     * @param  createdTs  CreatedTsEnum value for createdTs.
     * @param  modifiedTs  ModifiedTsEnum value for modifiedTs.
     */
    public Sort8(
            LocationIdEnum locationId,
            TitleEnum title,
            IdEnum id,
            CreatedTsEnum createdTs,
            ModifiedTsEnum modifiedTs) {
        this.locationId = locationId;
        this.title = title;
        this.id = id;
        this.createdTs = createdTs;
        this.modifiedTs = modifiedTs;
    }

    /**
     * Getter for LocationId.
     * @return Returns the LocationIdEnum
     */
    @JsonGetter("location_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LocationIdEnum getLocationId() {
        return locationId;
    }

    /**
     * Setter for LocationId.
     * @param locationId Value for LocationIdEnum
     */
    @JsonSetter("location_id")
    public void setLocationId(LocationIdEnum locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for Title.
     * @return Returns the TitleEnum
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TitleEnum getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for TitleEnum
     */
    @JsonSetter("title")
    public void setTitle(TitleEnum title) {
        this.title = title;
    }

    /**
     * Getter for Id.
     * @return Returns the IdEnum
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IdEnum getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for IdEnum
     */
    @JsonSetter("id")
    public void setId(IdEnum id) {
        this.id = id;
    }

    /**
     * Getter for CreatedTs.
     * @return Returns the CreatedTsEnum
     */
    @JsonGetter("created_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CreatedTsEnum getCreatedTs() {
        return createdTs;
    }

    /**
     * Setter for CreatedTs.
     * @param createdTs Value for CreatedTsEnum
     */
    @JsonSetter("created_ts")
    public void setCreatedTs(CreatedTsEnum createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * Getter for ModifiedTs.
     * @return Returns the ModifiedTsEnum
     */
    @JsonGetter("modified_ts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ModifiedTsEnum getModifiedTs() {
        return modifiedTs;
    }

    /**
     * Setter for ModifiedTs.
     * @param modifiedTs Value for ModifiedTsEnum
     */
    @JsonSetter("modified_ts")
    public void setModifiedTs(ModifiedTsEnum modifiedTs) {
        this.modifiedTs = modifiedTs;
    }

    /**
     * Converts this Sort8 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Sort8 [" + "locationId=" + locationId + ", title=" + title + ", id=" + id
                + ", createdTs=" + createdTs + ", modifiedTs=" + modifiedTs + "]";
    }

    /**
     * Builds a new {@link Sort8.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Sort8.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .locationId(getLocationId())
                .title(getTitle())
                .id(getId())
                .createdTs(getCreatedTs())
                .modifiedTs(getModifiedTs());
        return builder;
    }

    /**
     * Class to build instances of {@link Sort8}.
     */
    public static class Builder {
        private LocationIdEnum locationId;
        private TitleEnum title;
        private IdEnum id;
        private CreatedTsEnum createdTs;
        private ModifiedTsEnum modifiedTs;



        /**
         * Setter for locationId.
         * @param  locationId  LocationIdEnum value for locationId.
         * @return Builder
         */
        public Builder locationId(LocationIdEnum locationId) {
            this.locationId = locationId;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  TitleEnum value for title.
         * @return Builder
         */
        public Builder title(TitleEnum title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  IdEnum value for id.
         * @return Builder
         */
        public Builder id(IdEnum id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for createdTs.
         * @param  createdTs  CreatedTsEnum value for createdTs.
         * @return Builder
         */
        public Builder createdTs(CreatedTsEnum createdTs) {
            this.createdTs = createdTs;
            return this;
        }

        /**
         * Setter for modifiedTs.
         * @param  modifiedTs  ModifiedTsEnum value for modifiedTs.
         * @return Builder
         */
        public Builder modifiedTs(ModifiedTsEnum modifiedTs) {
            this.modifiedTs = modifiedTs;
            return this;
        }

        /**
         * Builds a new {@link Sort8} object using the set fields.
         * @return {@link Sort8}
         */
        public Sort8 build() {
            return new Sort8(locationId, title, id, createdTs, modifiedTs);
        }
    }
}
