/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for V1TagsRequest type.
 */
public class V1TagsRequest {
    private String locationId;
    private String title;

    /**
     * Default constructor.
     */
    public V1TagsRequest() {
    }

    /**
     * Initialization constructor.
     * @param  locationId  String value for locationId.
     * @param  title  String value for title.
     */
    public V1TagsRequest(
            String locationId,
            String title) {
        this.locationId = locationId;
        this.title = title;
    }

    /**
     * Getter for LocationId.
     * Location ID
     * @return Returns the String
     */
    @JsonGetter("location_id")
    public String getLocationId() {
        return locationId;
    }

    /**
     * Setter for LocationId.
     * Location ID
     * @param locationId Value for String
     */
    @JsonSetter("location_id")
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    /**
     * Getter for Title.
     * Tag Title
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Tag Title
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Converts this V1TagsRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "V1TagsRequest [" + "locationId=" + locationId + ", title=" + title + "]";
    }

    /**
     * Builds a new {@link V1TagsRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link V1TagsRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(locationId, title);
        return builder;
    }

    /**
     * Class to build instances of {@link V1TagsRequest}.
     */
    public static class Builder {
        private String locationId;
        private String title;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  locationId  String value for locationId.
         * @param  title  String value for title.
         */
        public Builder(String locationId, String title) {
            this.locationId = locationId;
            this.title = title;
        }

        /**
         * Setter for locationId.
         * @param  locationId  String value for locationId.
         * @return Builder
         */
        public Builder locationId(String locationId) {
            this.locationId = locationId;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Builds a new {@link V1TagsRequest} object using the set fields.
         * @return {@link V1TagsRequest}
         */
        public V1TagsRequest build() {
            return new V1TagsRequest(locationId, title);
        }
    }
}
