/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package tech.fortis.sandbox.api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import tech.fortis.sandbox.api.http.client.HttpContext;

/**
 * This is a model class for Response401tokenException type.
 */
public class Response401tokenException
        extends ApiException {
    private static final long serialVersionUID = 1180906893965101385L;
    private Integer statusCode;
    private String error;
    private String message;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public Response401tokenException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for StatusCode.
     * Response code
     * @return Returns the Integer
     */
    @JsonGetter("statusCode")
    public Integer getStatusCode() {
        return this.statusCode;
    }

    /**
     * Setter for StatusCode.
     * Response code
     * @param statusCode Value for Integer
     */
    @JsonSetter("statusCode")
    private void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * Getter for Error.
     * Unauthorized
     * @return Returns the String
     */
    @JsonGetter("error")
    public String getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * Unauthorized
     * @param error Value for String
     */
    @JsonSetter("error")
    private void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for Message.
     * Invalid token
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessage() {
        return this.message;
    }

    /**
     * Setter for Message.
     * Invalid token
     * @param message Value for String
     */
    @JsonSetter("message")
    private void setMessage(String message) {
        this.message = message;
    }
}
