/*
 * NullableLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import localhost3000.ApiHelper;
import localhost3000.AuthManager;
import localhost3000.Configuration;
import localhost3000.exceptions.ApiException;
import localhost3000.http.Headers;
import localhost3000.http.client.HttpCallback;
import localhost3000.http.client.HttpClient;
import localhost3000.http.client.HttpContext;
import localhost3000.http.request.HttpRequest;
import localhost3000.http.response.HttpResponse;
import localhost3000.http.response.HttpStringResponse;
import localhost3000.models.DynamicResponse;
import localhost3000.models.NullableScalarTypeContainer;

/**
 * This class lists all the endpoints of the groups.
 */
public final class BodyParamsController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public BodyParamsController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }

    /**
     * Initializes the controller with HTTPCallback.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     * @param httpCallback    Callback to be called before and after the HTTP call.
     */
    public BodyParamsController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        super(config, httpClient, authManagers, httpCallback);
    }

    /**
     * @param  allNullableSetToNull  Required parameter: Example:
     * @param  nullableScalarType  Required parameter: Example:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse createSendNullableScalarTypeContainerInBody(
            final boolean allNullableSetToNull,
            final NullableScalarTypeContainer nullableScalarType) throws ApiException, IOException {
        HttpRequest request = buildCreateSendNullableScalarTypeContainerInBodyRequest(
                allNullableSetToNull, nullableScalarType);
        HttpResponse response = getClientInstance().execute(request, false);
        HttpContext context = new HttpContext(request, response);

        return handleCreateSendNullableScalarTypeContainerInBodyResponse(context);
    }

    /**
     * @param  allNullableSetToNull  Required parameter: Example:
     * @param  nullableScalarType  Required parameter: Example:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> createSendNullableScalarTypeContainerInBodyAsync(
            final boolean allNullableSetToNull,
            final NullableScalarTypeContainer nullableScalarType) {
        return makeHttpCallAsync(() -> buildCreateSendNullableScalarTypeContainerInBodyRequest(
                allNullableSetToNull, nullableScalarType),
            request -> getClientInstance().executeAsync(request, false),
            context -> handleCreateSendNullableScalarTypeContainerInBodyResponse(context));
    }

    /**
     * Builds the HttpRequest object for createSendNullableScalarTypeContainerInBody.
     */
    private HttpRequest buildCreateSendNullableScalarTypeContainerInBodyRequest(
            final boolean allNullableSetToNull,
            final NullableScalarTypeContainer nullableScalarType) throws JsonProcessingException {
        //the base uri for api requests
        String baseUri = config.getBaseUri();

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/body/sendNullableTypeContainer");

        //load all query parameters
        Map<String, Object> queryParameters = new HashMap<>();
        queryParameters.put("allNullableSetToNull", allNullableSetToNull);

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("user-agent", BaseController.userAgent);
        headers.add("accept", "application/json");
        headers.add("content-type", "application/json");

        //prepare and invoke the API call request to fetch the response
        String bodyJson = ApiHelper.serialize(nullableScalarType);
        HttpRequest request = getClientInstance().postBody(queryBuilder, headers, queryParameters,
                bodyJson);

        // Invoke the callback before request if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onBeforeRequest(request);
        }

        return request;
    }

    /**
     * Processes the response for createSendNullableScalarTypeContainerInBody.
     * @return An object of type DynamicResponse
     */
    private DynamicResponse handleCreateSendNullableScalarTypeContainerInBodyResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onAfterResponse(context);
        }

        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        DynamicResponse result = new DynamicResponse(response);

        return result;
    }

}