/*
 * AnyOfScalarModelsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.controllers;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import localhost3000.ApiHelper;
import localhost3000.AuthManager;
import localhost3000.Configuration;
import localhost3000.exceptions.ApiException;
import localhost3000.http.Headers;
import localhost3000.http.client.HttpCallback;
import localhost3000.http.client.HttpClient;
import localhost3000.http.client.HttpContext;
import localhost3000.http.request.HttpRequest;
import localhost3000.http.response.HttpResponse;
import localhost3000.http.response.HttpStringResponse;
import localhost3000.models.AnyOfContainerOfOneOf;
import localhost3000.models.GetAnyofContainerOfOneofInput;

/**
 * This class lists all the endpoints of the groups.
 */
public final class MixPrimitiveTypesInResponseBodyController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public MixPrimitiveTypesInResponseBodyController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }

    /**
     * Initializes the controller with HTTPCallback.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     * @param httpCallback    Callback to be called before and after the HTTP call.
     */
    public MixPrimitiveTypesInResponseBodyController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        super(config, httpClient, authManagers, httpCallback);
    }

    /**
     * @param  input  GetAnyofContainerOfOneofInput object containing request parameters
     * @return    Returns the AnyOfContainerOfOneOf response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public AnyOfContainerOfOneOf getAnyofContainerOfOneof(
            final GetAnyofContainerOfOneofInput input) throws ApiException, IOException {
        HttpRequest request = buildGetAnyofContainerOfOneofRequest(input);
        HttpResponse response = getClientInstance().execute(request, false);
        HttpContext context = new HttpContext(request, response);

        return handleGetAnyofContainerOfOneofResponse(context);
    }

    /**
     * @param  input  GetAnyofContainerOfOneofInput object containing request parameters
     * @return    Returns the AnyOfContainerOfOneOf response from the API call
     */
    public CompletableFuture<AnyOfContainerOfOneOf> getAnyofContainerOfOneofAsync(
            final GetAnyofContainerOfOneofInput input) {
        return makeHttpCallAsync(() -> buildGetAnyofContainerOfOneofRequest(input),
            request -> getClientInstance().executeAsync(request, false),
            context -> handleGetAnyofContainerOfOneofResponse(context));
    }

    /**
     * Builds the HttpRequest object for getAnyofContainerOfOneof.
     */
    private HttpRequest buildGetAnyofContainerOfOneofRequest(
            final GetAnyofContainerOfOneofInput input) {
        //the base uri for api requests
        String baseUri = config.getBaseUri();

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/anyof/oneof/response/multiLevel");

        //load all query parameters
        Map<String, Object> queryParameters = new HashMap<>();
        queryParameters.put("isPrimitiveType", input.getIsPrimitiveType());
        queryParameters.put("isAtEndpointLevel", input.getIsAtEndpointLevel());
        queryParameters.put("hasDiscriminator", input.getHasDiscriminator());

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("user-agent", BaseController.userAgent);
        headers.add("accept", "application/json");

        //prepare and invoke the API call request to fetch the response
        HttpRequest request = getClientInstance().get(queryBuilder, headers, queryParameters,
                null);

        // Invoke the callback before request if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onBeforeRequest(request);
        }

        return request;
    }

    /**
     * Processes the response for getAnyofContainerOfOneof.
     * @return An object of type AnyOfContainerOfOneOf
     */
    private AnyOfContainerOfOneOf handleGetAnyofContainerOfOneofResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onAfterResponse(context);
        }

        //Error handling using HTTP status codes
        int responseCode = response.getStatusCode();

        if (responseCode == 400) {
            throw new ApiException("", context);
        }
        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        String responseBody = ((HttpStringResponse) response).getBody();
        AnyOfContainerOfOneOf result = ApiHelper.deserialize(responseBody,
                AnyOfContainerOfOneOf.class);

        return result;
    }

}