/*
 * AnyOfScalarModelsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.Map;
import localhost3000.models.containers.ArrayOfMapFlagOfMapCaseValue;

/**
 * This is a model class for ArrayOfMapFlagOfMapCase type.
 */
public class ArrayOfMapFlagOfMapCase {
    private List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value;

    /**
     * Default constructor.
     */
    public ArrayOfMapFlagOfMapCase() {
    }

    /**
     * Initialization constructor.
     * @param  value  List of String, value for value.
     */
    public ArrayOfMapFlagOfMapCase(
            List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value) {
        this.value = value;
    }

    /**
     * Getter for Value.
     * @return Returns the List of String, ArrayOfMapFlagOfMapCaseValue
     */
    @JsonGetter("value")
    public List<Map<String, ArrayOfMapFlagOfMapCaseValue>> getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for List of String, ArrayOfMapFlagOfMapCaseValue
     */
    @JsonSetter("value")
    public void setValue(List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value) {
        this.value = value;
    }

    /**
     * Converts this ArrayOfMapFlagOfMapCase into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ArrayOfMapFlagOfMapCase [" + "value=" + value + "]";
    }

    /**
     * Builds a new {@link ArrayOfMapFlagOfMapCase.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ArrayOfMapFlagOfMapCase.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value);
        return builder;
    }

    /**
     * Class to build instances of {@link ArrayOfMapFlagOfMapCase}.
     */
    public static class Builder {
        private List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  List of String, value for value.
         */
        public Builder(List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value) {
            this.value = value;
        }

        /**
         * Setter for value.
         * @param  value  List of String, value for value.
         * @return Builder
         */
        public Builder value(List<Map<String, ArrayOfMapFlagOfMapCaseValue>> value) {
            this.value = value;
            return this;
        }

        /**
         * Builds a new {@link ArrayOfMapFlagOfMapCase} object using the set fields.
         * @return {@link ArrayOfMapFlagOfMapCase}
         */
        public ArrayOfMapFlagOfMapCase build() {
            return new ArrayOfMapFlagOfMapCase(value);
        }
    }
}
