/*
 * AnyOfScalarModelsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import localhost3000.models.containers.OuterArrayCaseValue;

/**
 * This is a model class for OuterArrayCase type.
 */
public class OuterArrayCase {
    private List<OuterArrayCaseValue> value;

    /**
     * Default constructor.
     */
    public OuterArrayCase() {
    }

    /**
     * Initialization constructor.
     * @param  value  List of OuterArrayCaseValue value for value.
     */
    public OuterArrayCase(
            List<OuterArrayCaseValue> value) {
        this.value = value;
    }

    /**
     * Getter for Value.
     * @return Returns the List of OuterArrayCaseValue
     */
    @JsonGetter("value")
    public List<OuterArrayCaseValue> getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for List of OuterArrayCaseValue
     */
    @JsonSetter("value")
    public void setValue(List<OuterArrayCaseValue> value) {
        this.value = value;
    }

    /**
     * Converts this OuterArrayCase into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OuterArrayCase [" + "value=" + value + "]";
    }

    /**
     * Builds a new {@link OuterArrayCase.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OuterArrayCase.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value);
        return builder;
    }

    /**
     * Class to build instances of {@link OuterArrayCase}.
     */
    public static class Builder {
        private List<OuterArrayCaseValue> value;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  List of OuterArrayCaseValue value for value.
         */
        public Builder(List<OuterArrayCaseValue> value) {
            this.value = value;
        }

        /**
         * Setter for value.
         * @param  value  List of OuterArrayCaseValue value for value.
         * @return Builder
         */
        public Builder value(List<OuterArrayCaseValue> value) {
            this.value = value;
            return this;
        }

        /**
         * Builds a new {@link OuterArrayCase} object using the set fields.
         * @return {@link OuterArrayCase}
         */
        public OuterArrayCase build() {
            return new OuterArrayCase(value);
        }
    }
}
