/*
 * AnyOfScalarModelsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SendAnyofArrayOfArrayOfMapFlagInput type.
 */
public class SendAnyofArrayOfArrayOfMapFlagInput {
    private boolean isPrimitiveType;
    private boolean isAtEndpointLevel;
    private boolean hasDiscriminator;
    private ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase;

    /**
     * Default constructor.
     */
    public SendAnyofArrayOfArrayOfMapFlagInput() {
    }

    /**
     * Initialization constructor.
     * @param  isPrimitiveType  boolean value for isPrimitiveType.
     * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
     * @param  hasDiscriminator  boolean value for hasDiscriminator.
     * @param  arrayOfArrayOfMapFlagCase  ArrayOfArrayOfMapFlagCase value for
     *         arrayOfArrayOfMapFlagCase.
     */
    public SendAnyofArrayOfArrayOfMapFlagInput(
            boolean isPrimitiveType,
            boolean isAtEndpointLevel,
            boolean hasDiscriminator,
            ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase) {
        this.isPrimitiveType = isPrimitiveType;
        this.isAtEndpointLevel = isAtEndpointLevel;
        this.hasDiscriminator = hasDiscriminator;
        this.arrayOfArrayOfMapFlagCase = arrayOfArrayOfMapFlagCase;
    }

    /**
     * Getter for IsPrimitiveType.
     * @return Returns the boolean
     */
    @JsonGetter("isPrimitiveType")
    public boolean getIsPrimitiveType() {
        return isPrimitiveType;
    }

    /**
     * Setter for IsPrimitiveType.
     * @param isPrimitiveType Value for boolean
     */
    @JsonSetter("isPrimitiveType")
    public void setIsPrimitiveType(boolean isPrimitiveType) {
        this.isPrimitiveType = isPrimitiveType;
    }

    /**
     * Getter for IsAtEndpointLevel.
     * @return Returns the boolean
     */
    @JsonGetter("isAtEndpointLevel")
    public boolean getIsAtEndpointLevel() {
        return isAtEndpointLevel;
    }

    /**
     * Setter for IsAtEndpointLevel.
     * @param isAtEndpointLevel Value for boolean
     */
    @JsonSetter("isAtEndpointLevel")
    public void setIsAtEndpointLevel(boolean isAtEndpointLevel) {
        this.isAtEndpointLevel = isAtEndpointLevel;
    }

    /**
     * Getter for HasDiscriminator.
     * @return Returns the boolean
     */
    @JsonGetter("hasDiscriminator")
    public boolean getHasDiscriminator() {
        return hasDiscriminator;
    }

    /**
     * Setter for HasDiscriminator.
     * @param hasDiscriminator Value for boolean
     */
    @JsonSetter("hasDiscriminator")
    public void setHasDiscriminator(boolean hasDiscriminator) {
        this.hasDiscriminator = hasDiscriminator;
    }

    /**
     * Getter for ArrayOfArrayOfMapFlagCase.
     * @return Returns the ArrayOfArrayOfMapFlagCase
     */
    @JsonGetter("arrayOfArrayOfMapFlagCase")
    public ArrayOfArrayOfMapFlagCase getArrayOfArrayOfMapFlagCase() {
        return arrayOfArrayOfMapFlagCase;
    }

    /**
     * Setter for ArrayOfArrayOfMapFlagCase.
     * @param arrayOfArrayOfMapFlagCase Value for ArrayOfArrayOfMapFlagCase
     */
    @JsonSetter("arrayOfArrayOfMapFlagCase")
    public void setArrayOfArrayOfMapFlagCase(ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase) {
        this.arrayOfArrayOfMapFlagCase = arrayOfArrayOfMapFlagCase;
    }

    /**
     * Converts this SendAnyofArrayOfArrayOfMapFlagInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SendAnyofArrayOfArrayOfMapFlagInput [" + "isPrimitiveType=" + isPrimitiveType
                + ", isAtEndpointLevel=" + isAtEndpointLevel + ", hasDiscriminator="
                + hasDiscriminator + ", arrayOfArrayOfMapFlagCase=" + arrayOfArrayOfMapFlagCase
                + "]";
    }

    /**
     * Builds a new {@link SendAnyofArrayOfArrayOfMapFlagInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SendAnyofArrayOfArrayOfMapFlagInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isPrimitiveType, isAtEndpointLevel, hasDiscriminator,
                arrayOfArrayOfMapFlagCase);
        return builder;
    }

    /**
     * Class to build instances of {@link SendAnyofArrayOfArrayOfMapFlagInput}.
     */
    public static class Builder {
        private boolean isPrimitiveType;
        private boolean isAtEndpointLevel;
        private boolean hasDiscriminator;
        private ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isPrimitiveType  boolean value for isPrimitiveType.
         * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
         * @param  hasDiscriminator  boolean value for hasDiscriminator.
         * @param  arrayOfArrayOfMapFlagCase  ArrayOfArrayOfMapFlagCase value for
         *         arrayOfArrayOfMapFlagCase.
         */
        public Builder(boolean isPrimitiveType, boolean isAtEndpointLevel, boolean hasDiscriminator,
                ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase) {
            this.isPrimitiveType = isPrimitiveType;
            this.isAtEndpointLevel = isAtEndpointLevel;
            this.hasDiscriminator = hasDiscriminator;
            this.arrayOfArrayOfMapFlagCase = arrayOfArrayOfMapFlagCase;
        }

        /**
         * Setter for isPrimitiveType.
         * @param  isPrimitiveType  boolean value for isPrimitiveType.
         * @return Builder
         */
        public Builder isPrimitiveType(boolean isPrimitiveType) {
            this.isPrimitiveType = isPrimitiveType;
            return this;
        }

        /**
         * Setter for isAtEndpointLevel.
         * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
         * @return Builder
         */
        public Builder isAtEndpointLevel(boolean isAtEndpointLevel) {
            this.isAtEndpointLevel = isAtEndpointLevel;
            return this;
        }

        /**
         * Setter for hasDiscriminator.
         * @param  hasDiscriminator  boolean value for hasDiscriminator.
         * @return Builder
         */
        public Builder hasDiscriminator(boolean hasDiscriminator) {
            this.hasDiscriminator = hasDiscriminator;
            return this;
        }

        /**
         * Setter for arrayOfArrayOfMapFlagCase.
         * @param  arrayOfArrayOfMapFlagCase  ArrayOfArrayOfMapFlagCase value for
         *         arrayOfArrayOfMapFlagCase.
         * @return Builder
         */
        public Builder arrayOfArrayOfMapFlagCase(
                ArrayOfArrayOfMapFlagCase arrayOfArrayOfMapFlagCase) {
            this.arrayOfArrayOfMapFlagCase = arrayOfArrayOfMapFlagCase;
            return this;
        }

        /**
         * Builds a new {@link SendAnyofArrayOfArrayOfMapFlagInput} object using the set fields.
         * @return {@link SendAnyofArrayOfArrayOfMapFlagInput}
         */
        public SendAnyofArrayOfArrayOfMapFlagInput build() {
            return new SendAnyofArrayOfArrayOfMapFlagInput(isPrimitiveType, isAtEndpointLevel,
                    hasDiscriminator, arrayOfArrayOfMapFlagCase);
        }
    }
}
