/*
 * AnyOfScalarModelsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost3000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SendAnyofInnerArrayInput type.
 */
public class SendAnyofInnerArrayInput {
    private boolean isPrimitiveType;
    private boolean isAtEndpointLevel;
    private boolean hasDiscriminator;
    private InnerArrayCase innerArrayCase;

    /**
     * Default constructor.
     */
    public SendAnyofInnerArrayInput() {
    }

    /**
     * Initialization constructor.
     * @param  isPrimitiveType  boolean value for isPrimitiveType.
     * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
     * @param  hasDiscriminator  boolean value for hasDiscriminator.
     * @param  innerArrayCase  InnerArrayCase value for innerArrayCase.
     */
    public SendAnyofInnerArrayInput(
            boolean isPrimitiveType,
            boolean isAtEndpointLevel,
            boolean hasDiscriminator,
            InnerArrayCase innerArrayCase) {
        this.isPrimitiveType = isPrimitiveType;
        this.isAtEndpointLevel = isAtEndpointLevel;
        this.hasDiscriminator = hasDiscriminator;
        this.innerArrayCase = innerArrayCase;
    }

    /**
     * Getter for IsPrimitiveType.
     * @return Returns the boolean
     */
    @JsonGetter("isPrimitiveType")
    public boolean getIsPrimitiveType() {
        return isPrimitiveType;
    }

    /**
     * Setter for IsPrimitiveType.
     * @param isPrimitiveType Value for boolean
     */
    @JsonSetter("isPrimitiveType")
    public void setIsPrimitiveType(boolean isPrimitiveType) {
        this.isPrimitiveType = isPrimitiveType;
    }

    /**
     * Getter for IsAtEndpointLevel.
     * @return Returns the boolean
     */
    @JsonGetter("isAtEndpointLevel")
    public boolean getIsAtEndpointLevel() {
        return isAtEndpointLevel;
    }

    /**
     * Setter for IsAtEndpointLevel.
     * @param isAtEndpointLevel Value for boolean
     */
    @JsonSetter("isAtEndpointLevel")
    public void setIsAtEndpointLevel(boolean isAtEndpointLevel) {
        this.isAtEndpointLevel = isAtEndpointLevel;
    }

    /**
     * Getter for HasDiscriminator.
     * @return Returns the boolean
     */
    @JsonGetter("hasDiscriminator")
    public boolean getHasDiscriminator() {
        return hasDiscriminator;
    }

    /**
     * Setter for HasDiscriminator.
     * @param hasDiscriminator Value for boolean
     */
    @JsonSetter("hasDiscriminator")
    public void setHasDiscriminator(boolean hasDiscriminator) {
        this.hasDiscriminator = hasDiscriminator;
    }

    /**
     * Getter for InnerArrayCase.
     * @return Returns the InnerArrayCase
     */
    @JsonGetter("innerArrayCase")
    public InnerArrayCase getInnerArrayCase() {
        return innerArrayCase;
    }

    /**
     * Setter for InnerArrayCase.
     * @param innerArrayCase Value for InnerArrayCase
     */
    @JsonSetter("innerArrayCase")
    public void setInnerArrayCase(InnerArrayCase innerArrayCase) {
        this.innerArrayCase = innerArrayCase;
    }

    /**
     * Converts this SendAnyofInnerArrayInput into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SendAnyofInnerArrayInput [" + "isPrimitiveType=" + isPrimitiveType
                + ", isAtEndpointLevel=" + isAtEndpointLevel + ", hasDiscriminator="
                + hasDiscriminator + ", innerArrayCase=" + innerArrayCase + "]";
    }

    /**
     * Builds a new {@link SendAnyofInnerArrayInput.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SendAnyofInnerArrayInput.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isPrimitiveType, isAtEndpointLevel, hasDiscriminator,
                innerArrayCase);
        return builder;
    }

    /**
     * Class to build instances of {@link SendAnyofInnerArrayInput}.
     */
    public static class Builder {
        private boolean isPrimitiveType;
        private boolean isAtEndpointLevel;
        private boolean hasDiscriminator;
        private InnerArrayCase innerArrayCase;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isPrimitiveType  boolean value for isPrimitiveType.
         * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
         * @param  hasDiscriminator  boolean value for hasDiscriminator.
         * @param  innerArrayCase  InnerArrayCase value for innerArrayCase.
         */
        public Builder(boolean isPrimitiveType, boolean isAtEndpointLevel, boolean hasDiscriminator,
                InnerArrayCase innerArrayCase) {
            this.isPrimitiveType = isPrimitiveType;
            this.isAtEndpointLevel = isAtEndpointLevel;
            this.hasDiscriminator = hasDiscriminator;
            this.innerArrayCase = innerArrayCase;
        }

        /**
         * Setter for isPrimitiveType.
         * @param  isPrimitiveType  boolean value for isPrimitiveType.
         * @return Builder
         */
        public Builder isPrimitiveType(boolean isPrimitiveType) {
            this.isPrimitiveType = isPrimitiveType;
            return this;
        }

        /**
         * Setter for isAtEndpointLevel.
         * @param  isAtEndpointLevel  boolean value for isAtEndpointLevel.
         * @return Builder
         */
        public Builder isAtEndpointLevel(boolean isAtEndpointLevel) {
            this.isAtEndpointLevel = isAtEndpointLevel;
            return this;
        }

        /**
         * Setter for hasDiscriminator.
         * @param  hasDiscriminator  boolean value for hasDiscriminator.
         * @return Builder
         */
        public Builder hasDiscriminator(boolean hasDiscriminator) {
            this.hasDiscriminator = hasDiscriminator;
            return this;
        }

        /**
         * Setter for innerArrayCase.
         * @param  innerArrayCase  InnerArrayCase value for innerArrayCase.
         * @return Builder
         */
        public Builder innerArrayCase(InnerArrayCase innerArrayCase) {
            this.innerArrayCase = innerArrayCase;
            return this;
        }

        /**
         * Builds a new {@link SendAnyofInnerArrayInput} object using the set fields.
         * @return {@link SendAnyofInnerArrayInput}
         */
        public SendAnyofInnerArrayInput build() {
            return new SendAnyofInnerArrayInput(isPrimitiveType, isAtEndpointLevel,
                    hasDiscriminator, innerArrayCase);
        }
    }
}
